/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a3.piccross.server;

import a3.piccross.helper.Logger;

import javax.swing.*;

/**
 *
 * @author wpho
 */
public class ServerMainForm extends javax.swing.JFrame {

    /**
     * Creates new form ServerMainForm
     */
    private GameServer gameServer;
    public ServerMainForm(GameServer gameServer) {
        initComponents();
        gameServer.getLogger().setTextArea(jTextArea1);
        this.gameServer = gameServer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();
        cbFinalize = new javax.swing.JCheckBox();
        btnEnd = new javax.swing.JButton();
        taLog = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piccross Server");
        setPreferredSize(new java.awt.Dimension(680, 400));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piccross.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Port:");

        tfPort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPort.setText("12345");
        tfPort.setToolTipText("");
        tfPort.setName("tfPort"); // NOI18N

        btnExecute.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExecute.setText("Execute");
        btnExecute.setToolTipText("");
        btnExecute.setActionCommand("");
        btnExecute.setName("btnExecute"); // NOI18N
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        cbFinalize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbFinalize.setText("Finalize");

        btnEnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnd.setText("End");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        taLog.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExecute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbFinalize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnd)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(taLog)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecute)
                    .addComponent(cbFinalize)
                    .addComponent(btnEnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taLog, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        if (gameServer.isRunning()){
            JOptionPane.showMessageDialog(null, "Server already running!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            if (tfPort.getText() != null || !tfPort.getText().isEmpty()){
                try{
                    int port = Integer.parseInt(tfPort.getText());
                    gameServer.execute(port);
                    btnExecute.setEnabled(false);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please enter valid port!", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }



    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        // TODO add your handling code here:
        if (gameServer.isRunning()){
            gameServer.end();
        }else{
            JOptionPane.showMessageDialog(null, "Please firs run!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnExecute;
    private javax.swing.JCheckBox cbFinalize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane taLog;
    private javax.swing.JTextField tfPort;
    // End of variables declaration//GEN-END:variables
}
