/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a3.piccross.client;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;

/**
 *
 * @author wpho
 */
public class ClientGameForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientGameForm
     * @param gameController
     */

    private final GameController gameController;
    private final Timer timer;
    private final int[][] gameBoard;
    private int currentPoint;
    private int piccrossCount;

    private JLabel[][] labels;
    public ClientGameForm(GameController gameController, int[][] gameBoard) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.gameController = gameController;
        this.gameBoard = gameBoard;
        tfTime.setText("0");
        timer = new Timer(1000, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tfTime.setText(Integer.parseInt(tfTime.getText()) + 1 + "");
            }
        });

        labels = new JLabel[5][5];
        labels[0][0] = l00;
        labels[0][1] = l01;
        labels[0][2] = l02;
        labels[0][3] = l03;
        labels[0][4] = l04;

        labels[1][0] = l10;
        labels[1][1] = l11;
        labels[1][2] = l12;
        labels[1][3] = l13;
        labels[1][4] = l14;

        labels[2][0] = l20;
        labels[2][1] = l21;
        labels[2][2] = l22;
        labels[2][3] = l23;
        labels[2][4] = l24;

        labels[3][0] = l30;
        labels[3][1] = l31;
        labels[3][2] = l32;
        labels[3][3] = l33;
        labels[3][4] = l34;

        labels[4][0] = l40;
        labels[4][1] = l41;
        labels[4][2] = l42;
        labels[4][3] = l43;
        labels[4][4] = l44;

        taLog.append("Solution\n");
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                labels[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        JLabel label = (JLabel)e.getSource();
                        String text = label.getText();
                        if ("0".equals(text)){
                            label.setText("1");
                            label.setForeground(Color.green);
                            label.setBackground(Color.green);
                        }else{
                            label.setText("0");
                            label.setForeground(Color.yellow);
                            label.setBackground(Color.yellow);
                        }
                    }
                });

                taLog.append(gameBoard[i][j] + "");
            }
            taLog.append("\n");
        }

        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbMark = new javax.swing.JCheckBox();
        tx0 = new javax.swing.JLabel();
        tx1 = new javax.swing.JLabel();
        tx2 = new javax.swing.JLabel();
        tx3 = new javax.swing.JLabel();
        tx4 = new javax.swing.JLabel();
        ty0 = new javax.swing.JLabel();
        l00 = new javax.swing.JLabel();
        l01 = new javax.swing.JLabel();
        l02 = new javax.swing.JLabel();
        l03 = new javax.swing.JLabel();
        l04 = new javax.swing.JLabel();
        ty1 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        ty2 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        ty3 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l34 = new javax.swing.JLabel();
        ty4 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfPoints = new javax.swing.JTextField();
        btnPiccross = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfTime = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        menuTop = new javax.swing.JMenuBar();
        mGame = new javax.swing.JMenu();
        mHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel1.setLayout(new java.awt.GridLayout(6, 6, 1, 1));

        cbMark.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbMark.setText("Mark");
        cbMark.setEnabled(false);
        cbMark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarkActionPerformed(evt);
            }
        });
        jPanel1.add(cbMark);

        tx0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tx0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx0.setText("X0");
        jPanel1.add(tx0);

        tx1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tx1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx1.setText("X1");
        jPanel1.add(tx1);

        tx2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx2.setText("X2");
        jPanel1.add(tx2);

        tx3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx3.setText("X3");
        jPanel1.add(tx3);

        tx4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tx4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx4.setText("X4");
        jPanel1.add(tx4);

        ty0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ty0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ty0.setText("Y0");
        jPanel1.add(ty0);

        l00.setBackground(new java.awt.Color(255, 255, 0));
        l00.setForeground(new java.awt.Color(255, 255, 0));
        l00.setText("0");
        l00.setToolTipText("");
        l00.setMinimumSize(new java.awt.Dimension(100, 100));
        l00.setName(""); // NOI18N
        l00.setOpaque(true);
        jPanel1.add(l00);

        l01.setBackground(new java.awt.Color(255, 255, 0));
        l01.setForeground(new java.awt.Color(255, 255, 0));
        l01.setText("0");
        l01.setToolTipText("");
        l01.setMinimumSize(new java.awt.Dimension(100, 100));
        l01.setName(""); // NOI18N
        l01.setOpaque(true);
        jPanel1.add(l01);

        l02.setBackground(new java.awt.Color(255, 255, 0));
        l02.setForeground(new java.awt.Color(255, 255, 0));
        l02.setText("0");
        l02.setToolTipText("");
        l02.setMinimumSize(new java.awt.Dimension(100, 100));
        l02.setName(""); // NOI18N
        l02.setOpaque(true);
        jPanel1.add(l02);

        l03.setBackground(new java.awt.Color(255, 255, 0));
        l03.setForeground(new java.awt.Color(255, 255, 0));
        l03.setText("0");
        l03.setToolTipText("");
        l03.setMinimumSize(new java.awt.Dimension(100, 100));
        l03.setName(""); // NOI18N
        l03.setOpaque(true);
        jPanel1.add(l03);

        l04.setBackground(new java.awt.Color(255, 255, 0));
        l04.setForeground(new java.awt.Color(255, 255, 0));
        l04.setText("0");
        l04.setToolTipText("");
        l04.setMinimumSize(new java.awt.Dimension(100, 100));
        l04.setName(""); // NOI18N
        l04.setOpaque(true);
        jPanel1.add(l04);

        ty1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ty1.setText("Y1");
        jPanel1.add(ty1);

        l10.setBackground(new java.awt.Color(255, 255, 0));
        l10.setForeground(new java.awt.Color(255, 255, 0));
        l10.setText("0");
        l10.setToolTipText("");
        l10.setMinimumSize(new java.awt.Dimension(100, 100));
        l10.setName(""); // NOI18N
        l10.setOpaque(true);
        jPanel1.add(l10);

        l11.setBackground(new java.awt.Color(255, 255, 0));
        l11.setForeground(new java.awt.Color(255, 255, 0));
        l11.setText("0");
        l11.setToolTipText("");
        l11.setMinimumSize(new java.awt.Dimension(100, 100));
        l11.setName(""); // NOI18N
        l11.setOpaque(true);
        jPanel1.add(l11);

        l12.setBackground(new java.awt.Color(255, 255, 0));
        l12.setForeground(new java.awt.Color(255, 255, 0));
        l12.setText("0");
        l12.setToolTipText("");
        l12.setMinimumSize(new java.awt.Dimension(100, 100));
        l12.setName(""); // NOI18N
        l12.setOpaque(true);
        jPanel1.add(l12);

        l13.setBackground(new java.awt.Color(255, 255, 0));
        l13.setForeground(new java.awt.Color(255, 255, 0));
        l13.setText("0");
        l13.setToolTipText("");
        l13.setMinimumSize(new java.awt.Dimension(100, 100));
        l13.setName(""); // NOI18N
        l13.setOpaque(true);
        jPanel1.add(l13);

        l14.setBackground(new java.awt.Color(255, 255, 0));
        l14.setForeground(new java.awt.Color(255, 255, 0));
        l14.setText("0");
        l14.setToolTipText("");
        l14.setMinimumSize(new java.awt.Dimension(100, 100));
        l14.setName(""); // NOI18N
        l14.setOpaque(true);
        jPanel1.add(l14);

        ty2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ty2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ty2.setText("Y2");
        jPanel1.add(ty2);

        l20.setBackground(new java.awt.Color(255, 255, 0));
        l20.setForeground(new java.awt.Color(255, 255, 0));
        l20.setText("0");
        l20.setToolTipText("");
        l20.setMinimumSize(new java.awt.Dimension(100, 100));
        l20.setName(""); // NOI18N
        l20.setOpaque(true);
        jPanel1.add(l20);

        l21.setBackground(new java.awt.Color(255, 255, 0));
        l21.setForeground(new java.awt.Color(255, 255, 0));
        l21.setText("0");
        l21.setToolTipText("");
        l21.setMinimumSize(new java.awt.Dimension(100, 100));
        l21.setName(""); // NOI18N
        l21.setOpaque(true);
        jPanel1.add(l21);

        l22.setBackground(new java.awt.Color(255, 255, 0));
        l22.setForeground(new java.awt.Color(255, 255, 0));
        l22.setText("0");
        l22.setToolTipText("");
        l22.setMinimumSize(new java.awt.Dimension(100, 100));
        l22.setName(""); // NOI18N
        l22.setOpaque(true);
        jPanel1.add(l22);

        l23.setBackground(new java.awt.Color(255, 255, 0));
        l23.setForeground(new java.awt.Color(255, 255, 0));
        l23.setText("0");
        l23.setToolTipText("");
        l23.setMinimumSize(new java.awt.Dimension(100, 100));
        l23.setName(""); // NOI18N
        l23.setOpaque(true);
        jPanel1.add(l23);

        l24.setBackground(new java.awt.Color(255, 255, 0));
        l24.setForeground(new java.awt.Color(255, 255, 0));
        l24.setText("0");
        l24.setToolTipText("");
        l24.setMinimumSize(new java.awt.Dimension(100, 100));
        l24.setName(""); // NOI18N
        l24.setOpaque(true);
        jPanel1.add(l24);

        ty3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ty3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ty3.setText("Y3");
        jPanel1.add(ty3);

        l30.setBackground(new java.awt.Color(255, 255, 0));
        l30.setForeground(new java.awt.Color(255, 255, 0));
        l30.setText("0");
        l30.setToolTipText("");
        l30.setMinimumSize(new java.awt.Dimension(100, 100));
        l30.setName(""); // NOI18N
        l30.setOpaque(true);
        jPanel1.add(l30);

        l31.setBackground(new java.awt.Color(255, 255, 0));
        l31.setForeground(new java.awt.Color(255, 255, 0));
        l31.setText("0");
        l31.setToolTipText("");
        l31.setMinimumSize(new java.awt.Dimension(100, 100));
        l31.setName(""); // NOI18N
        l31.setOpaque(true);
        jPanel1.add(l31);

        l32.setBackground(new java.awt.Color(255, 255, 0));
        l32.setForeground(new java.awt.Color(255, 255, 0));
        l32.setText("0");
        l32.setToolTipText("");
        l32.setMinimumSize(new java.awt.Dimension(100, 100));
        l32.setName(""); // NOI18N
        l32.setOpaque(true);
        jPanel1.add(l32);

        l33.setBackground(new java.awt.Color(255, 255, 0));
        l33.setForeground(new java.awt.Color(255, 255, 0));
        l33.setText("0");
        l33.setToolTipText("");
        l33.setMinimumSize(new java.awt.Dimension(100, 100));
        l33.setName(""); // NOI18N
        l33.setOpaque(true);
        jPanel1.add(l33);

        l34.setBackground(new java.awt.Color(255, 255, 0));
        l34.setForeground(new java.awt.Color(255, 255, 0));
        l34.setText("0");
        l34.setToolTipText("");
        l34.setMinimumSize(new java.awt.Dimension(100, 100));
        l34.setName(""); // NOI18N
        l34.setOpaque(true);
        jPanel1.add(l34);

        ty4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ty4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ty4.setText("Y4");
        jPanel1.add(ty4);

        l40.setBackground(new java.awt.Color(255, 255, 0));
        l40.setForeground(new java.awt.Color(255, 255, 0));
        l40.setText("0");
        l40.setToolTipText("");
        l40.setMinimumSize(new java.awt.Dimension(100, 100));
        l40.setName(""); // NOI18N
        l40.setOpaque(true);
        jPanel1.add(l40);

        l41.setBackground(new java.awt.Color(255, 255, 0));
        l41.setForeground(new java.awt.Color(255, 255, 0));
        l41.setText("0");
        l41.setToolTipText("");
        l41.setMinimumSize(new java.awt.Dimension(100, 100));
        l41.setName(""); // NOI18N
        l41.setOpaque(true);
        jPanel1.add(l41);

        l42.setBackground(new java.awt.Color(255, 255, 0));
        l42.setForeground(new java.awt.Color(255, 255, 0));
        l42.setText("0");
        l42.setToolTipText("");
        l42.setMinimumSize(new java.awt.Dimension(100, 100));
        l42.setName(""); // NOI18N
        l42.setOpaque(true);
        jPanel1.add(l42);

        l43.setBackground(new java.awt.Color(255, 255, 0));
        l43.setForeground(new java.awt.Color(255, 255, 0));
        l43.setText("0");
        l43.setToolTipText("");
        l43.setMinimumSize(new java.awt.Dimension(100, 100));
        l43.setName(""); // NOI18N
        l43.setOpaque(true);
        jPanel1.add(l43);

        l44.setBackground(new java.awt.Color(255, 255, 0));
        l44.setForeground(new java.awt.Color(255, 255, 0));
        l44.setText("0");
        l44.setToolTipText("");
        l44.setMinimumSize(new java.awt.Dimension(100, 100));
        l44.setName(""); // NOI18N
        l44.setOpaque(true);
        jPanel1.add(l44);

        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane1.setViewportView(taLog);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Points:");

        tfPoints.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPoints.setEnabled(false);

        btnPiccross.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPiccross.setText("PICCROSS");
        btnPiccross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiccrossActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Time:");

        tfTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTime.setEnabled(false);

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        mGame.setText("Game");
        menuTop.add(mGame);

        mHelp.setText("Help");
        menuTop.add(mHelp);

        setJMenuBar(menuTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPoints))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnPiccross, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnPiccross)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnReset)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMarkActionPerformed

    private void btnPiccrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiccrossActionPerformed
        // TODO add your handling code here:
        currentPoint = (200 - Integer.parseInt(tfTime.getText())) / ++piccrossCount;
        tfPoints.setText(currentPoint + "");

        int[][] currentBoard = new int[5][5];
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if ("0".equals(labels[i][j].getText())){
                    currentBoard[i][j] = 0;
                } else{
                    currentBoard[i][j] = 1;
                }
            }
        }

        if (Arrays.deepEquals(currentBoard, gameBoard)) {
            timer.stop();
            btnPiccross.setEnabled(false);
            btnReset.setEnabled(false);
            cbMark.setSelected(true);
            gameController.win(currentPoint + "", tfTime.getText());
        }else {
            JOptionPane.showMessageDialog(null, "Please check again!", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnPiccrossActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i <5; i++) {
            for (int j = 0; j < 5; j++) {
                labels[i][j].setBackground(Color.yellow);
                labels[i][j].setForeground(Color.yellow);
                labels[i][j].setText("0");
            }
        }
        currentPoint = 0;
        tfPoints.setText("0");
        tfTime.setText(0 + "");
        timer.restart();

    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPiccross;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbMark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l00;
    private javax.swing.JLabel l01;
    private javax.swing.JLabel l02;
    private javax.swing.JLabel l03;
    private javax.swing.JLabel l04;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l34;
    private javax.swing.JLabel l40;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l44;
    private javax.swing.JMenu mGame;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuBar menuTop;
    private javax.swing.JTextArea taLog;
    private javax.swing.JTextField tfPoints;
    private javax.swing.JTextField tfTime;
    private javax.swing.JLabel tx0;
    private javax.swing.JLabel tx1;
    private javax.swing.JLabel tx2;
    private javax.swing.JLabel tx3;
    private javax.swing.JLabel tx4;
    private javax.swing.JLabel ty0;
    private javax.swing.JLabel ty1;
    private javax.swing.JLabel ty2;
    private javax.swing.JLabel ty3;
    private javax.swing.JLabel ty4;
    // End of variables declaration//GEN-END:variables
}
